WX_INCLUDE = /c/Darek/app/wxWidgets/include/


all:
	g++ main.cpp main.h serialConfigurator.cpp serialConfigurator.h MainWindow.cpp MainWindow.h `wx-config --cxxflags --libs` -o serconf -I$(WX_INCLUDE) -I../gfx

